### ISSUE TITLE
Failed to load sector 

### ISSUE THREAD

**Issue by Puneethsp** [cognitedata/reveal#1571]
Hi,
I have downloaded and configured Reveal and hosted as local. https://localhost:3000/

The Viewer is loading examples which provided in github "sector_0.i3d" but when exported from blender those i3d files could not able to view in Viewer.
Getting "Failed to load sector" error.

Could you please help me that how to create Reveal supportable  .i3d file to view in  Viewer.

Thank you
![Failedtoloadsector](https://user-images.githubusercontent.com/55481752/125583401-ff008700-7a81-4bbb-80e4-85643fd78301.jpg)

**Comment by Puneethsp** [comment]
Hi anyone could you please reply for this 

Thank you.

**Comment by christjt** [comment]
Hello @Puneethsp, sorry for the late reply, most of the team has been on vacation in July. Reveal at this time only consumes models from Cognite Data Fusion (https://www.cognite.com/en/cognite-data-fusion).

**Comment by christjt** [comment]
More information on Cognite's 3D processing pipeline can be found at https://www.cognite.com/en/cognite-data-fusion/3d-and-photogrammetry-pipelines
