### ISSUE TITLE
`worldToNormalizedViewportCoordinates` does not support devices with a non 1-to-1 pixel ratio

### ISSUE THREAD

**Issue by hayer** [cognitedata/reveal#1672]
The current implementation of `worldToNormalizedViewportCoordinates` seems to not support pixel ratios different from 1.

```
const pixelRatio = 1; // renderer.getPixelRatio();
...

const x = (position.x + 1) / (scaleX * pixelRatio * 2);
const y = (-position.y + 1) / (scaleY * pixelRatio * 2);
```

**Comment by haakonflatval-cognite** [comment]
We ended up addressing this issue with PR #1700. I don't know what specific issue (if any) you experienced with the previous implementation, but it was hopefully addressed by that PR.
