### ISSUE TITLE
logMetrics = false doesnt actually disable usage statistics in Cognite3dViewer

### ISSUE THREAD

**Issue by hkot1991** [cognitedata/reveal#1699]
We are using the Cognite3dViwer an passing the argument logMetric = false to the viewer, however the code will still log usage statistics.  Documented code says: "Might be used to disable usage statistics." 
But logMetrics seems to be dropped when createRevealManagerOptions is called

Is there anyway to actually disable usage statistics today? If not can this be something we can expect in a next release?

**Comment by larsmoa** [comment]
Thats certainly something we will look into and have fixed for next release (within a couple of weeks).

**Comment by haakonflatval-cognite** [comment]
The PR for fixing this has been merged. It will be part of the next release (2.2).
