### ISSUE TITLE
Refresh token for sector loading when token has expired

### ISSUE THREAD

**Issue by hkot1991** [cognitedata/reveal#1740]
It seems like there is no refresh of token for sector loading.

Recreated using the cad basic example in your documentation
Navigate inwards on the platform, see that sectors are loaded without a problem. 
Leave browser window open for more than 1 hour, then try to navigate around the model.
When sectors are loaded now we will get a 401 response since the token is expired in the js console:
![image](https://user-images.githubusercontent.com/61226854/145181734-aa1a6838-f021-4885-aebb-d06e210629b5.png)
Followed by these errors:
![image](https://user-images.githubusercontent.com/61226854/145181785-82ca3480-345d-4706-b627-8c5d79244417.png)

But no visual indication to the user that something went wrong (other that that the sectors will not be displayed)

Is there any plan to handle this case of refreshing tokens? Or some possiblity to detect this error in the code? 😄

**Comment by haakonflatval-cognite** [comment]
Hi! We have been looking at a solution to this which refreshes the token. It will be implemented in the next release.

Thanks for reporting!

**Comment by christjt** [comment]
Closing this as it has been implemented and released with 2.3.0.
