### ISSUE TITLE
Mobile performance

### ISSUE THREAD

**Issue by hkot1991** [cognitedata/reveal#1954]
Im wondering if there has been much testing on you side on mobile devices. Has there?

The reason why I'm asking is because there is an requirement for our application that it should be able to run on ios mobile devices,
however we are experiencing some crashes when running the viewer with our models. So I'm wondering if maybe you have had some issues with this aswell.

And also are there any optimalisation work in your roadmap for performance?

**Comment by christjt** [comment]
We have had some issues in with some complex models on low end devices (are you running on EX-devices?). If you are crashing it is most likely running out of memory. What is the hardware you are running on?

**Comment by hkot1991** [comment]
We are trying to support ios devices, mobile and ipad. We currently are experiencing crashes on iPhone Xs, 11 and 13. And also on iPad Mini 4, ipad Mini 5, ipad 6 and Ipad Pro
We have seen that the more powerfull once will take "more effort" to crash, but we have been able to reproduce it on all these devices. 

As you say, it seems to be that the devices are running out of memory. But we are also seeing some spikes in CPU usage when loading the model (seems to stem from reveal parser). It might seem that the code doesnt care about the devices resources available and just tries to go for a "load all" approach.

Are you working on anything that might improve the running out of memory issues and/or preformance measurements?

**Comment by espenrl** [comment]
Is there any performance benefit to use the V9 format?

**Comment by christjt** [comment]
Sorry for the late reply @espenrl, yes there should be a much better performance implications for v9. There are multiple reasons for this:

- Most of the parsing has been offloaded to the backend (now does a lot of the mathematical conversions formally handled by rust WASM parsers in reveal).
- The tree structure we use is now a lot more balanced, tighter and flatter, such that we can more granular control which sectors we load, ultimately causing less overload of data.
- The sector culler we use for v8 is not GPU driven anymore which frees up the resource and also has way less overhead when determining which sectors to load.

There are other minor details which separate v8 and v9 as well but these are the major factors. We are planning to deprecate v8 for Reveal 4.0.0 which will probably happen around EOY 2022.

**Comment by christjt** [comment]
Closing this as we don't have any actionable for this atm. We are shipping a dynamic resolution feature based on camera movement, and in addition to other performance improvements, I think mobile is working ok atm. Please reopen with specifics if you are still experiencing issues.
