### ISSUE TITLE
3.1.0 defaults to using Medium SSAO on mobile devices

### ISSUE THREAD

**Issue by Strepto** [cognitedata/reveal#2236]
https://github.com/cognitedata/reveal/blob/a4d35b882b458956c27c7f109d9f00bd52ff6163/viewer/packages/api/src/public/migration/renderOptionsHelpers.ts#L140-L142

There is a bug here where the default fallthrough of `restrictSsaoOptionBasedOnDevice` is the input value, and the input value might be `undefined`. This makes the switch here
https://github.com/cognitedata/reveal/blob/a4d35b882b458956c27c7f109d9f00bd52ff6163/viewer/packages/api/src/public/migration/renderOptionsHelpers.ts#L69-L72

just use the default value, which is "SSAO medium", and this makes performance on mobile unusable. Its easy to work around in the client by specifying the quality to `'disabled`, but it might be nice for new users fo the library to not have to specify the ssaoQualityHint. 

(Remark: i have looked at this for about 10 minutes and did not actually verify this is a fix)

**Comment by Strepto** [comment]
Also:

The isMobileOrTablet check does not detect iPad when they have "Request Desktop Website" (Which is the default).

An ugly workaround could be: 
```
function iOS() {
  return [
    'iPad Simulator',
    'iPhone Simulator',
    'iPod Simulator',
    'iPad',
    'iPhone',
    'iPod'
  ].includes(navigator.platform)
  // iPad on iOS 13+ detection ('Request Desktop Website' workaround)
  || (navigator.userAgent.includes("Mac") && "ontouchend" in document) // Super hacky and will fail when Macs get touch...
}
```

**Comment by christjt** [comment]
Thanks for reporting!

I'll try to get a patch out tomorrow to fix this.

**Comment by christjt** [comment]
Hey @Strepto,

Would it be possible for you to verify this fix: https://github.com/cognitedata/reveal/pull/2239?

**Comment by christjt** [comment]
@Strepto Has been merged now. Is this something you need us to release asap. or is it ok to defer?

**Comment by Strepto** [comment]
No rush for us.

Feel free to close the issue 🥇
