### ISSUE TITLE
Problems with sector selection

### ISSUE THREAD

**Issue by vegasten** [cognitedata/reveal#2347]
We are having some problem with sector selection after changing to V9. Sectors are popping in and out at times when we would expect otherwise. We are studying the weight functions and have a couple questions/observations in that regard. 

From the weighting based on frustum depth, it seems that the first 5% of "NearFarRange" is given a low weight. We might have far planes at a few hundres meters and near planes at ~0, which means that the first tens of meters are weighted low. The importance is set quite low, but it still seems to create some problems for us.

From the weighting based on level it might seem that your sector structure is quite flat? 
We currently have multiple levels, so the weighting  will just make sure level 1 is prioritized highly, and not make level 2 be prioritized above level 3. 

It is also important for us to have a way to guarantee that everything inside a given distance is correct and fully rendered. Similar to how it was done with "highDetailProximityThreshold" in V8. 

Do you have any tips or suggestions for how we can improve our sector selection? Is it a possibility to expose the weight handling so we can create our own weighting functions, for instance? 

We can also set up a meeting to discuss this, if that is of interest to you.

**Comment by larsmoa** [comment]
Hi Vegard - can you send me a mail on lars.moastuen@cognite.com so we can set up a meeting on this?

**Comment by vegasten** [comment]
Closing this because we're using a custom sector culler and are not experiencing this problem anymore.
