### ISSUE TITLE
Fragment Interpolation causes wrong TreeIndex lookup on some GPUs

### ISSUE THREAD

**Issue by Strepto** [cognitedata/reveal#2363]
The title is a hypothesis, but the fix seems to work. The issue does NOT occur on certain Intel GPUs, but its reproducible on Nvidia, Mac, and iOS GPUs.

This may also have been the cause of #2176 

It seems to be a problem with fragment interpolation on some (most) GPUs that cause issues when TreeIndexes are high (+2 million), and that will introduce noise in the 3D model when filters are applied, AND when Picking based on TreeIndex.

The effect looks like this, when for instance highlighting is applied: 

![image](https://user-images.githubusercontent.com/3185998/187393466-600ea11a-100d-46fb-86b8-9dcc2274c71e.png)

Importantly this also affects picking, which may get the wrong TreeIndex (often off by 1 or up to 2) for a meshpart due to this issue.

The issue occurs frequently on TreeIndexes over approx 2_000_000 , and gets worse with higher numbers.

Our hypothesis is that the fragment interpolation causes an inaccuracy that makes the interpolation operation roundtrip give significant variance in the output fragment treeIndex. See a description of the possible algorithm here: https://stackoverflow.com/questions/24441631/how-exactly-does-opengl-do-perspectively-correct-linear-interpolation

The fix seems to be to apply `flat` to the fragment shader. See: https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Interpolation_qualifiers

**Comment by christjt** [comment]
Fixed with #2364
