### ISSUE TITLE
Consider memoizing the output of setModelRenderLayers to save performance

### ISSUE THREAD

**Issue by Strepto** [cognitedata/reveal#2604]
As discussed a few weeks ago the linked path is potentially performance intensive, and is invoked every render.

The output should never change given that no IndexSet is updated in the meantime. Consider if its worth looking into optimizing this

https://github.com/cognitedata/reveal/blob/39fd25eadb0f488b4c279db5854ef95e314a9d51/viewer/packages/rendering/src/utilities/renderUtilities.ts#L243-L272

The performance issue here is bigger on large models, so it might be worth investigating. 

In a random frame in the chrome debugger, on a model with normal three-indexes this uses 50% of the java-script time (across a 2 second timespan when moving camera). Sampled on a high-end computer. 
![image](https://user-images.githubusercontent.com/3185998/197520836-c4ba50ea-c7c5-4eab-a8c9-81779b655fc8.png)

**Comment by christjt** [comment]
Thanks for reporting. I think the fix for this is to move this logic on load / unload and when styling changes. Will track a task for this.

**Comment by christjt** [comment]
This has been resolved in https://github.com/cognitedata/reveal/pull/2896, please reopen if you experience any issues.
