### ISSUE TITLE
PixelPicking Depth Precision

### ISSUE THREAD

**Issue by Strepto** [cognitedata/reveal#2606]
Hi, the new measure tool uses the Pixel Picking to place measurements.

When using this on larger models, we see that the measuring point does not stick to the surface as we expected when we move closer. This indicates that measure points are not accurate (at least when placed on a distance)

Example from reveal: 
![image](https://user-images.githubusercontent.com/3185998/197553971-6ab06d9b-6dfc-4251-af47-7446902575b0.png)

I assume this is from depth buffer precision issues, but I have not found any quick fixes to check the depth buffer precision. 

Do you have any thoughts on this issue?

**Comment by christjt** [comment]
Hey, this is known from our side and we are looking into it. Will come back to you when I get some more time to investigate.

**Comment by larsmoa** [comment]
@Strepto : can you try disabling automatic near/far plane and set in manually? See https://cognitedata.github.io/reveal-docs/docs/api/classes/cognite_reveal.DefaultCameraManager/#automaticnearfarplane (access manager by using `viewer.cameraManager` and casting to `DefaultCameraManager`.

**Comment by christjt** [comment]
This has now been fixed, and is merged into master (https://github.com/cognitedata/reveal/pull/2885). Please reopen if you are still experiencing issues.
