### ISSUE TITLE
Docs for loading 360 Images does not include `datamodels`

### ISSUE THREAD

**Issue by joao-mbn** [cognitedata/reveal#4615]
According to the [Reveal docs](https://cognitedata.github.io/reveal-docs/docs/examples/image360)

> Once the data is ingested, a set of 360 images can be added to the viewer with viewer.add360ImageSet(...). datasource describes the source data type used for storing the 360 images. At this time, the only valid datasource is 'events', but you can expect more to be added in the future.

The same docs suggests ingesting data following instructions on [cdf docs](https://docs.cognite.com/cdf/3d/guides/360images_upload/)

The project seemed to have everything configured: schema, views, files, etc. The files at `Image360` view had a `site_id` on its metadata that was equal to an `externalId` of `Image360Collection`. With that, I was able to load data for 6 out of 8 image collections I had, by going as the docs suggests:

```typescript 
viewer.add360ImageSet('events', { site_id: model.name });
```

That didn't work for 2 collections, though. I noticed that the query for `events/list` returned empty for the offending ids, but with data for the others. The query `files/list` returned data for all ids, but it didn't make a difference.

Looking to a scene configured in CDF where all 8 collections are loaded, I noticed that it didn't query either events or files list endpoints. Then, I noticed that there is another way of adding 360 Image collections:

```typescript 
viewer.add360ImageSet('datamodels', { image360CollectionExternalId: model.name, space: model.space });
```

The latter method is not documented. Talking with Christian Flasshoff, he said that using `events` is a deprecated way for loading the collections and the new way is actually `datamodels`. 

The docs should reflect this change.

**Comment by christjt** [comment]
Thank you for identifying this gap in our documentation. We will update it as soon as possible.

**Comment by haakonflatval-cognite** [comment]
@joao-mbn We made a small update in the documentation in the above PR. I'm closing the issue soon, let me know if you don't think the changes above solves the issue
