### ISSUE TITLE
CameraManager interface containing only a subset of DefaultCameraManager properties leading to type errors

### ISSUE THREAD

**Issue by joao-mbn** [cognitedata/reveal#4677]
According to the [docs](https://cognitedata.github.io/reveal-docs/docs/examples/controlsmodes), I'd be able to `setCameraControlsOptions` on the camera manager, but I get typescript errors by doing exactly what the docs says:

```typescript
const newControlsOptions = {
  mouseWheelAction: 'zoomToCursor',
  changeCameraTargetOnClick: true,
};

viewer.cameraManager.setCameraControlsOptions(newControlsOptions);
```

Error message: `Property 'setCameraControlsOptions' does not exist on type 'CameraManager'.`

I have to cast the `cameraManager` to `DefaultCameraManger` first, so that the errors stop:

```typescript
;(viewer.cameraManager as DefaultCameraManager).setCameraControlsOptions(newControlsOptions)
```

I think the `cameraManager` type should be improved in so that this casting wouldn't be necessary. Since the camera manager is an argument to the `Cognite3DViewer`, passed when creating an instance, I believe that some play with generics, using the DefaultCameraManager as default interface when no custom camera manager is passed could be be a solution.

**Comment by haakonflatval-cognite** [comment]
Hi! As mentioned in the meeting today, we are not happy with the way the camera managers are handled today, and want to re-evaluate how it's exposed for the 5.0 release. Interesting idea with using generics :thinking: I'm a little skeptical to go with that approach, since it would make it impossible to set a new camera manager on the 3D viewer in run-time - but I'll think about whether there's something else we can do. As for the documentation error, I'll try to fix that as fast as possible :+1:

**Comment by haakonflatval-cognite** [comment]
Ah - sorry, on further thought, the reason we don't do the casting in the examples, is that those examples are pure Javascript, so types are not allowed, and casting is unnecessary. I'll make a note about it above the example snippet instead

**Comment by joao-mbn** [comment]
Yes, I believe that working with generics wouldn't handle well changing the camera manager once the instance is created.

Hinting to that in the docs is a good first step. 

While not perfect, I believe that having a type narrowing utility exposed could be better than casting, because casting is an informed guess (or belief) while type narrowing is a surety.

so you could expose something like:

```typescript
function isDefaultCameraManager(cameraManager: CameraManager): cameraManager is DefaultCameraManager {
// ...
}
```

**Comment by haakonflatval-cognite** [comment]
I like that idea better - I have added the type guard and updated the docs again in the previous PR

**Comment by haakonflatval-cognite** [comment]
The PR has been merged - I'll close this as solved now :+1:
